### ISSUE TITLE
Can't convert Yolov2

### ISSUE THREAD

**Issue by shiomi326** [jinyu121/DW2TF#13]
Hi, I had a error when I tried to convert yolov2. Any ideas? thank you.
OS: Ubuntu 18.04
Cuda: 10.0
tensorflow-gpu: 1.13.1
```
31 Tensor("yolov2/convolutional23/BiasAdd:0", shape=(?, 19, 19, 425), dtype=float32)
=> Ignore:  {'name': 'region', 'anchors': ['0.57273', '0.677385', '1.87446', '2.06253', '3.33843', '5.47434', '7.88282', '3.52778', '9.77052', '9.16828'], 'bias_match': '1', 'classes': '80', 'coords': '4', 'num': '5', 'softmax': '1', 'jitter': '.3', 'rescore': '1', 'object_scale': '5', 'noobject_scale': '1', 'class_scale': '1', 'coord_scale': '1', 'absolute': '1', 'thresh': '.6', 'random': '1'}
32 Tensor("yolov2/convolutional23/BiasAdd:0", shape=(?, 19, 19, 425), dtype=float32)
Traceback (most recent call last):
  File "/mnt/hdd1/dev/DW2TF/util/reader.py", line 84, in get_block
    line = next(line_getter)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 112, in <module>
    main(args)
  File "main.py", line 53, in main
    parse_net(args.layers, args.cfg, args.weights, args.training)
  File "main.py", line 25, in parse_net
    for ith, layer in enumerate(cfg_walker):
RuntimeError: generator raised StopIteration
```

**Comment by shiomi326** [comment]
hmm, It was not a problem of yolov2. 
I changed python from 3.7 to 3.6. and no error occurred this time.

**Comment by sjain-stanford** [comment]
@shiomi326 thanks for reporting, I've updated the README to caution the user of known issues with Python 3.7.
