### ISSUE TITLE
Converting Yolov3: ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by ManCuSa** [jinyu121/DW2TF#17]
Hi,

I'm trying to convert YOLOv3 model to tensorflow. I downloaded YOLOv3-416 model from here: https://pjreddie.com/darknet/yolo/

When I'm running this command:

`python3 main.py --cfg 'data/yolov3.cfg' --weights 'data/yolov3.weights' --output 'data/' --prefix 'yolov3/' --gpu 0`

I'm getting the following error:
`python3 main.py --cfg 'data/yolov3.cfg' --weights 'data/yolov3.weights' --output 'data/' --prefix 'yolov3/' --gpu 0
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    main(args)
  File "main.py", line 53, in main
    parse_net(args.layers, args.cfg, args.weights, args.training)
  File "main.py", line 25, in parse_net
    for ith, layer in enumerate(cfg_walker):
  File "/Users/mice/Desktop/DW2TF-master/util/reader.py", line 94, in get_block
    key, value = line[0:2]
ValueError: not enough values to unpack (expected 2, got 1)`

My python version is: Python 3.6.8 :: Anaconda, Inc.

Can you please help and tell how to convert that YOLOv3 model?

**Comment by ManCuSa** [comment]
The Issue was on my side. I had a problem with .cfg file. Sorry for the problem.
