### ISSUE TITLE
UnicodeDecodeError (Python 3.6.8)

### ISSUE THREAD

**Issue by jiiins** [jinyu121/DW2TF#36]
Trying to convert yolov3 with I get this error:
```
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    main(args)
  File "main.py", line 57, in main
    parse_net(args.layers, args.cfg, args.weights, args.training)
  File "main.py", line 25, in parse_net
    for ith, layer in enumerate(cfg_walker):
  File "/home/user/temp/DW2TF/util/reader.py", line 84, in get_block
    line = next(line_getter)
  File "/home/user/temp/DW2TF/util/reader.py", line 74, in _get_line
    for line in open(self.fnm):
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1241: ordinal not in range(128)
```
Command:
```
python3 main.py \
    --cfg 'data/yolov3.cfg' \
    --weights 'data/yolov3.weights' \
    --output 'data/' \
    --prefix 'yolov3/' \
    --gpu 0
```

**Comment by HongYg** [comment]
i have that too

UnicodeDecodeError: 'cp949' codec can't decode byte 0xc0 in position 1: illegal multibyte sequence
