### ISSUE TITLE
generator raised StopIteration

### ISSUE THREAD

**Issue by HongYg** [jinyu121/DW2TF#45]
python main.py --cfg testv3.cfg --weights testv3.weights --output data/ --prefix yolov3/ --gpu 0

C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From main.py:56: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From C:\cfg\DW2TF-master\DW2TF-master\util\cfg_layer.py:32: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

0 Tensor("yolov3/net1:0", shape=(?, 832, 832, 3), dtype=float32)
WARNING:tensorflow:From C:\Users\gaonpf\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py:507: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with verify_shape is deprecated and will be removed in a future version.
Instructions for updating:
Objects must now be the required shape or no shape can be specified
WARNING:tensorflow:From C:\cfg\DW2TF-master\DW2TF-master\util\cfg_layer.py:74: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
WARNING:tensorflow:From C:\cfg\DW2TF-master\DW2TF-master\util\cfg_layer.py:93: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
1 Tensor("yolov3/convolutional1/Activation:0", shape=(?, 832, 832, 32), dtype=float32)
2 Tensor("yolov3/convolutional2/Activation:0", shape=(?, 416, 416, 64), dtype=float32)
3 Tensor("yolov3/convolutional3/Activation:0", shape=(?, 416, 416, 32), dtype=float32)
4 Tensor("yolov3/convolutional4/Activation:0", shape=(?, 416, 416, 64), dtype=float32)
5 Tensor("yolov3/shortcut1:0", shape=(?, 416, 416, 64), dtype=float32)
6 Tensor("yolov3/convolutional5/Activation:0", shape=(?, 208, 208, 128), dtype=float32)
7 Tensor("yolov3/convolutional6/Activation:0", shape=(?, 208, 208, 64), dtype=float32)
8 Tensor("yolov3/convolutional7/Activation:0", shape=(?, 208, 208, 128), dtype=float32)
9 Tensor("yolov3/shortcut2:0", shape=(?, 208, 208, 128), dtype=float32)
10 Tensor("yolov3/convolutional8/Activation:0", shape=(?, 208, 208, 64), dtype=float32)
11 Tensor("yolov3/convolutional9/Activation:0", shape=(?, 208, 208, 128), dtype=float32)
12 Tensor("yolov3/shortcut3:0", shape=(?, 208, 208, 128), dtype=float32)
13 Tensor("yolov3/convolutional10/Activation:0", shape=(?, 104, 104, 256), dtype=float32)
14 Tensor("yolov3/convolutional11/Activation:0", shape=(?, 104, 104, 128), dtype=float32)
15 Tensor("yolov3/convolutional12/Activation:0", shape=(?, 104, 104, 256), dtype=float32)
16 Tensor("yolov3/shortcut4:0", shape=(?, 104, 104, 256), dtype=float32)
17 Tensor("yolov3/convolutional13/Activation:0", shape=(?, 104, 104, 128), dtype=float32)
18 Tensor("yolov3/convolutional14/Activation:0", shape=(?, 104, 104, 256), dtype=float32)
19 Tensor("yolov3/shortcut5:0", shape=(?, 104, 104, 256), dtype=float32)
20 Tensor("yolov3/convolutional15/Activation:0", shape=(?, 104, 104, 128), dtype=float32)
21 Tensor("yolov3/convolutional16/Activation:0", shape=(?, 104, 104, 256), dtype=float32)
22 Tensor("yolov3/shortcut6:0", shape=(?, 104, 104, 256), dtype=float32)
23 Tensor("yolov3/convolutional17/Activation:0", shape=(?, 104, 104, 128), dtype=float32)
24 Tensor("yolov3/convolutional18/Activation:0", shape=(?, 104, 104, 256), dtype=float32)
25 Tensor("yolov3/shortcut7:0", shape=(?, 104, 104, 256), dtype=float32)
26 Tensor("yolov3/convolutional19/Activation:0", shape=(?, 104, 104, 128), dtype=float32)
27 Tensor("yolov3/convolutional20/Activation:0", shape=(?, 104, 104, 256), dtype=float32)
28 Tensor("yolov3/shortcut8:0", shape=(?, 104, 104, 256), dtype=float32)
29 Tensor("yolov3/convolutional21/Activation:0", shape=(?, 104, 104, 128), dtype=float32)
30 Tensor("yolov3/convolutional22/Activation:0", shape=(?, 104, 104, 256), dtype=float32)
31 Tensor("yolov3/shortcut9:0", shape=(?, 104, 104, 256), dtype=float32)
32 Tensor("yolov3/convolutional23/Activation:0", shape=(?, 104, 104, 128), dtype=float32)
33 Tensor("yolov3/convolutional24/Activation:0", shape=(?, 104, 104, 256), dtype=float32)
34 Tensor("yolov3/shortcut10:0", shape=(?, 104, 104, 256), dtype=float32)
35 Tensor("yolov3/convolutional25/Activation:0", shape=(?, 104, 104, 128), dtype=float32)
36 Tensor("yolov3/convolutional26/Activation:0", shape=(?, 104, 104, 256), dtype=float32)
37 Tensor("yolov3/shortcut11:0", shape=(?, 104, 104, 256), dtype=float32)
38 Tensor("yolov3/convolutional27/Activation:0", shape=(?, 52, 52, 512), dtype=float32)
39 Tensor("yolov3/convolutional28/Activation:0", shape=(?, 52, 52, 256), dtype=float32)
40 Tensor("yolov3/convolutional29/Activation:0", shape=(?, 52, 52, 512), dtype=float32)
41 Tensor("yolov3/shortcut12:0", shape=(?, 52, 52, 512), dtype=float32)
42 Tensor("yolov3/convolutional30/Activation:0", shape=(?, 52, 52, 256), dtype=float32)
43 Tensor("yolov3/convolutional31/Activation:0", shape=(?, 52, 52, 512), dtype=float32)
44 Tensor("yolov3/shortcut13:0", shape=(?, 52, 52, 512), dtype=float32)
45 Tensor("yolov3/convolutional32/Activation:0", shape=(?, 52, 52, 256), dtype=float32)
46 Tensor("yolov3/convolutional33/Activation:0", shape=(?, 52, 52, 512), dtype=float32)
47 Tensor("yolov3/shortcut14:0", shape=(?, 52, 52, 512), dtype=float32)
48 Tensor("yolov3/convolutional34/Activation:0", shape=(?, 52, 52, 256), dtype=float32)
49 Tensor("yolov3/convolutional35/Activation:0", shape=(?, 52, 52, 512), dtype=float32)
50 Tensor("yolov3/shortcut15:0", shape=(?, 52, 52, 512), dtype=float32)
51 Tensor("yolov3/convolutional36/Activation:0", shape=(?, 52, 52, 256), dtype=float32)
52 Tensor("yolov3/convolutional37/Activation:0", shape=(?, 52, 52, 512), dtype=float32)
53 Tensor("yolov3/shortcut16:0", shape=(?, 52, 52, 512), dtype=float32)
54 Tensor("yolov3/convolutional38/Activation:0", shape=(?, 52, 52, 256), dtype=float32)
55 Tensor("yolov3/convolutional39/Activation:0", shape=(?, 52, 52, 512), dtype=float32)
56 Tensor("yolov3/shortcut17:0", shape=(?, 52, 52, 512), dtype=float32)
57 Tensor("yolov3/convolutional40/Activation:0", shape=(?, 52, 52, 256), dtype=float32)
58 Tensor("yolov3/convolutional41/Activation:0", shape=(?, 52, 52, 512), dtype=float32)
59 Tensor("yolov3/shortcut18:0", shape=(?, 52, 52, 512), dtype=float32)
60 Tensor("yolov3/convolutional42/Activation:0", shape=(?, 52, 52, 256), dtype=float32)
61 Tensor("yolov3/convolutional43/Activation:0", shape=(?, 52, 52, 512), dtype=float32)
62 Tensor("yolov3/shortcut19:0", shape=(?, 52, 52, 512), dtype=float32)
63 Tensor("yolov3/convolutional44/Activation:0", shape=(?, 26, 26, 1024), dtype=float32)
64 Tensor("yolov3/convolutional45/Activation:0", shape=(?, 26, 26, 512), dtype=float32)
65 Tensor("yolov3/convolutional46/Activation:0", shape=(?, 26, 26, 1024), dtype=float32)
66 Tensor("yolov3/shortcut20:0", shape=(?, 26, 26, 1024), dtype=float32)
67 Tensor("yolov3/convolutional47/Activation:0", shape=(?, 26, 26, 512), dtype=float32)
68 Tensor("yolov3/convolutional48/Activation:0", shape=(?, 26, 26, 1024), dtype=float32)
69 Tensor("yolov3/shortcut21:0", shape=(?, 26, 26, 1024), dtype=float32)
70 Tensor("yolov3/convolutional49/Activation:0", shape=(?, 26, 26, 512), dtype=float32)
71 Tensor("yolov3/convolutional50/Activation:0", shape=(?, 26, 26, 1024), dtype=float32)
72 Tensor("yolov3/shortcut22:0", shape=(?, 26, 26, 1024), dtype=float32)
73 Tensor("yolov3/convolutional51/Activation:0", shape=(?, 26, 26, 512), dtype=float32)
74 Tensor("yolov3/convolutional52/Activation:0", shape=(?, 26, 26, 1024), dtype=float32)
75 Tensor("yolov3/shortcut23:0", shape=(?, 26, 26, 1024), dtype=float32)
76 Tensor("yolov3/convolutional53/Activation:0", shape=(?, 26, 26, 512), dtype=float32)
77 Tensor("yolov3/convolutional54/Activation:0", shape=(?, 26, 26, 1024), dtype=float32)
78 Tensor("yolov3/convolutional55/Activation:0", shape=(?, 26, 26, 512), dtype=float32)
79 Tensor("yolov3/convolutional56/Activation:0", shape=(?, 26, 26, 1024), dtype=float32)
80 Tensor("yolov3/convolutional57/Activation:0", shape=(?, 26, 26, 512), dtype=float32)
81 Tensor("yolov3/convolutional58/Activation:0", shape=(?, 26, 26, 1024), dtype=float32)
82 Tensor("yolov3/convolutional59/BiasAdd:0", shape=(?, 26, 26, 255), dtype=float32)
83 Tensor("yolov3/convolutional59/BiasAdd:0", shape=(?, 26, 26, 255), dtype=float32)
84 Tensor("yolov3/route1:0", shape=(?, 26, 26, 512), dtype=float32)
85 Tensor("yolov3/convolutional60/Activation:0", shape=(?, 26, 26, 256), dtype=float32)
WARNING:tensorflow:From C:\cfg\DW2TF-master\DW2TF-master\util\cfg_layer.py:164: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.

86 Tensor("yolov3/upsample1:0", shape=(?, 52, 52, 256), dtype=float32)
87 Tensor("yolov3/route2:0", shape=(?, 52, 52, 768), dtype=float32)
88 Tensor("yolov3/convolutional61/Activation:0", shape=(?, 52, 52, 256), dtype=float32)
89 Tensor("yolov3/convolutional62/Activation:0", shape=(?, 52, 52, 512), dtype=float32)
90 Tensor("yolov3/convolutional63/Activation:0", shape=(?, 52, 52, 256), dtype=float32)
91 Tensor("yolov3/convolutional64/Activation:0", shape=(?, 52, 52, 512), dtype=float32)
92 Tensor("yolov3/convolutional65/Activation:0", shape=(?, 52, 52, 256), dtype=float32)
93 Tensor("yolov3/convolutional66/Activation:0", shape=(?, 52, 52, 512), dtype=float32)
94 Tensor("yolov3/convolutional67/BiasAdd:0", shape=(?, 52, 52, 255), dtype=float32)
95 Tensor("yolov3/convolutional67/BiasAdd:0", shape=(?, 52, 52, 255), dtype=float32)
96 Tensor("yolov3/route3:0", shape=(?, 52, 52, 256), dtype=float32)
97 Tensor("yolov3/convolutional68/Activation:0", shape=(?, 52, 52, 128), dtype=float32)
98 Tensor("yolov3/upsample2:0", shape=(?, 104, 104, 128), dtype=float32)
99 Tensor("yolov3/route4:0", shape=(?, 104, 104, 384), dtype=float32)
100 Tensor("yolov3/convolutional69/Activation:0", shape=(?, 104, 104, 128), dtype=float32)
101 Tensor("yolov3/convolutional70/Activation:0", shape=(?, 104, 104, 256), dtype=float32)
102 Tensor("yolov3/convolutional71/Activation:0", shape=(?, 104, 104, 128), dtype=float32)
103 Tensor("yolov3/convolutional72/Activation:0", shape=(?, 104, 104, 256), dtype=float32)
104 Tensor("yolov3/convolutional73/Activation:0", shape=(?, 104, 104, 128), dtype=float32)
105 Tensor("yolov3/convolutional74/Activation:0", shape=(?, 104, 104, 256), dtype=float32)
106 Tensor("yolov3/convolutional75/BiasAdd:0", shape=(?, 104, 104, 24), dtype=float32)
107 Tensor("yolov3/convolutional75/BiasAdd:0", shape=(?, 104, 104, 24), dtype=float32)
Traceback (most recent call last):
  File "C:\cfg\DW2TF-master\DW2TF-master\util\reader.py", line 84, in get_block
    line = next(line_getter)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 116, in <module>
    main(args)
  File "main.py", line 57, in main
    parse_net(args.layers, args.cfg, args.weights, args.training)
  File "main.py", line 25, in parse_net
    for ith, layer in enumerate(cfg_walker):
RuntimeError: generator raised StopIteration

why?

**Comment by HongYg** [comment]
I solved 
python 3.7->> python 3.6
