### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by pra-dan** [jinyu121/DW2TF#47]
I am converting YOLO v2-tiny model to TensorFlow. 
I downloaded the weights from the official site and saved them to the `data/` directory.
After running 
`!python3 main.py \
    --cfg 'data/yolov2.cfg' \
    --weights 'data/yolov2.weights' \
    --output 'data/' \
    --prefix 'yolov2/' \
    --gpu 0`
_I mistakenly renamed the yolov2-tiny files to yolov2 files, hence the paths to `cfg` and `weights` may seem wrong_

But this is what I get:
```
WARNING:tensorflow:From main.py:56: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

Traceback (most recent call last):
  File "main.py", line 116, in <module>
    main(args)
  File "main.py", line 57, in main
    parse_net(args.layers, args.cfg, args.weights, args.training)
  File "main.py", line 25, in parse_net
    for ith, layer in enumerate(cfg_walker):
  File "/content/DW2TF/util/reader.py", line 94, in get_block
    key, value = line[0:2]
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by pratayusha** [comment]
Hi  pra-dan ,
I had a similar problem because I was using incorrect cfg file.

Use below command,
wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov2.cfg
