### ISSUE TITLE
runtime error,i use windows pycharm to run this

### ISSUE THREAD

**Issue by hexin6688** [jinyu121/DW2TF#48]
Traceback (most recent call last):
  File "G:\darknet_to_tensorflow\DW2TF-1.2\util\reader.py", line 84, in get_block
    line = next(line_getter)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:/darknet_to_tensorflow/DW2TF-1.2/main.py", line 116, in <module>
    main(args)
  File "G:/darknet_to_tensorflow/DW2TF-1.2/main.py", line 57, in main
    parse_net(args.layers, args.cfg, args.weights, args.training)
  File "G:/darknet_to_tensorflow/DW2TF-1.2/main.py", line 25, in parse_net
    for ith, layer in enumerate(cfg_walker):
RuntimeError: generator raised StopIteration

**Comment by pshwetank** [comment]
Even I got the same issue while using it to convert YOLO V4 to TF graph.

**Comment by pshwetank** [comment]
It seems like there are some layers in the darknet that the script is not able to convert into tensorflow. Let me know which version of Yolo you implemented. It will help me debug the issue.

**Comment by yudharisandy** [comment]
@pshwetank i also got the same issue while converting YOLOv4 to TF graph. how can you solve the issues?
