### ISSUE TITLE
ValueError: ''yolov3-tiny/'net1' is not a valid scope name

### ISSUE THREAD

**Issue by Muhammad-Sharif-Ullah** [jinyu121/DW2TF#50]
Traceback (most recent call last):                                                                                                              
  File "main.py", line 116, in <module>                                                                                                         
    main(args)                                                                                                                                  
  File "main.py", line 57, in main                                                                                                              
    parse_net(args.layers, args.cfg, args.weights, args.training)                                                                               
  File "main.py", line 33, in parse_net                                                                                                         
    training=training, const_inits=const_inits, verbose=verbose)                                                                                
  File "D:\yolo\extra\DW2TF-1.2_v2\util\cfg_layer.py", line 198, in get_cfg_layer                                                               
    layer = _cfg_layer_dict.get(layer_name, cfg_ignore)(B, H, W, C, net, param, weights_walker, stack, output_index, scope, training, const_init
s, verbose)                                                                                                                                     
  File "D:\yolo\extra\DW2TF-1.2_v2\util\cfg_layer.py", line 32, in cfg_net                                                                      
    net = tf.compat.v1.placeholder(tf.float32, [None, width, height, channels], name=scope)                                                     
  File "C:\Users\MD-SHARIF-ULLAH\.virtualenvs\yolo-lBfTfznQ\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2630, in placeholde
r                                                                                                                                               
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)                                                                       
  File "C:\Users\MD-SHARIF-ULLAH\.virtualenvs\yolo-lBfTfznQ\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 6670, in placeh
older                                                                                                                                           
    "Placeholder", dtype=dtype, shape=shape, name=name)                                                                                         
  File "C:\Users\MD-SHARIF-ULLAH\.virtualenvs\yolo-lBfTfznQ\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 410, in 
_apply_op_helper                                                                                                                                
    with g.as_default(), ops.name_scope(name) as scope:                                                                                         
  File "C:\Users\MD-SHARIF-ULLAH\.virtualenvs\yolo-lBfTfznQ\lib\site-packages\tensorflow_core\python\framework\ops.py", line 6349, in __enter__ 
    return self._name_scope.__enter__()                                                                                                         
  File "c:\users\md-sharif-ullah\appdata\local\programs\python\python37\Lib\contextlib.py", line 112, in __enter__                              
    return next(self.gen)                                                                                                                       
  File "C:\Users\MD-SHARIF-ULLAH\.virtualenvs\yolo-lBfTfznQ\lib\site-packages\tensorflow_core\python\framework\ops.py", line 4132, in name_scope
                                                                                                                                                
    raise ValueError("'%s' is not a valid scope name" % name)                                                                                   
ValueError: ''yolov3-tiny/'net1' is not a valid scope name

**Comment by FranBesq** [comment]
Have you tried this ?
 "yolov3-tiny/'net1:0" #Note the :0
