### ISSUE TITLE
Getting Error: RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by lukerbs** [jinyu121/DW2TF#58]
Traceback (most recent call last):
  File "/Users/luke/Projects/DW2TF/util/reader.py", line 84, in get_block
    line = next(line_getter)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 117, in <module>
    main(args)
  File "main.py", line 58, in main
    parse_net(args.layers, args.cfg, args.weights, args.training)
  File "main.py", line 26, in parse_net
    for ith, layer in enumerate(cfg_walker):
RuntimeError: generator raised StopIteration

**Comment by PadalaKavya** [comment]
I am having the same issue
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/new_folder/DW2TF/util/reader.py", line 84, in get_block
    line = next(line_getter)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 116, in <module>
    main(args)
  File "main.py", line 57, in main
    parse_net(args.layers, args.cfg, args.weights, args.training)
  File "main.py", line 25, in parse_net
    for ith, layer in enumerate(cfg_walker):
RuntimeError: generator raised StopIteration

**Comment by PadalaKavya** [comment]
This can be resolve by using try and except in the "DW2TF/util/reader.py"
At line 84 add
try:
  ....
except stopIteration:
    return
