### ISSUE TITLE
Can't convert Yolov3-tiny to TensorFlow

### ISSUE THREAD

**Issue by zolkiBy** [jinyu121/DW2TF#8]
I'm trying to convert Yolov3-tiny model to TensorFlow.
cfg and weights file from https://pjreddie.com/darknet/yolo/ (Yolov3-tiny)
OS: Ubunty 16.04
command to convert:
```python3 main.py --cfg 'data/yolov3-tiny.cfg' --weights 'data/yolov3-tiny.weights' --output 'data/' --prefix 'yolov3/' --gpu 0```

Error:
```Traceback (most recent call last):
  File "test/anaconda3/envs/condaenv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 24 and 26. Shapes are [?,24,24] and [?,26,26]. for 'yolov3/route2' (op: 'ConcatV2') with input shapes: [?,24,24,128], [?,26,26,128], [] and with computed input tensors: input[2] = <-1>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 111, in <module>
    main(args)
  File "main.py", line 52, in main
    parse_net(args.layers, args.cfg, args.weights, args.training)
  File "main.py", line 32, in parse_net
    training=training, const_inits=const_inits, verbose=verbose)
  File "/test/DW2TF-master/util/cfg_layer.py", line 197, in get_cfg_layer
    layer = _cfg_layer_dict.get(layer_name, cfg_ignore)(B, H, W, C, net, param, weights_walker, stack, output_index, scope, training, const_inits, verbose)
  File "test/DW2TF-master/util/cfg_layer.py", line 131, in cfg_route
    net = tf.concat(nets, axis=-1, name=scope)
  File "test/anaconda3/envs/condaenv/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1124, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "test/anaconda3/envs/condaenv/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1033, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "test/anaconda3/envs/condaenv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "test/anaconda3/envs/condaenv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "test/anaconda3/envs/condaenv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "test/anaconda3/envs/condaenv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "test/anaconda3/envs/condaenv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 24 and 26. Shapes are [?,24,24] and [?,26,26]. for 'yolov3/route2' (op: 'ConcatV2') with input shapes: [?,24,24,128], [?,26,26,128], [] and with computed input tensors: input[2] = <-1>.
```

**Comment by sjain-stanford** [comment]
@zolkiBy Aha, this is an incompatibility issue due to a tiny difference in padding algorithms between darknet and tensorflow. In particular, layer 11 in yolov3-tiny is a `2x2` maxpool with `stride=1`, operating on `13x13x512` input. In darknet this produces an output that is `13x13x512`. However in tensorflow, it produces `12x12x512` (default padding is `valid`). Consecutive layers mismatch and concat complains.

As as fix I specify `same` padding, which works for this network (however it may not apply more generally). As long as darknet consistently uses this padding for maxpool, it should work fine.

@jinyu121 - could you add me as collaborator so I can fix/test/push? Alternately I can create a PR as usual.

#### darknet shapes:
```
$ ./darknet detect cfg/yolov3-tiny.cfg yolov3-tiny.weights data/dog.jpg

layer     filters    size              input                output
    0 conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16  0.150 BFLOPs
    1 max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16
    2 conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32  0.399 BFLOPs
    3 max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32
    4 conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64  0.399 BFLOPs
    5 max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64
    6 conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128  0.399 BFLOPs
    7 max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128
    8 conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256  0.399 BFLOPs
    9 max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256
   10 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512  0.399 BFLOPs
   11 max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512
   12 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024  1.595 BFLOPs
   13 conv    256  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 256  0.089 BFLOPs
   14 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512  0.399 BFLOPs
   15 conv    255  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x 255  0.044 BFLOPs
   16 yolo
   17 route  13
   18 conv    128  1 x 1 / 1    13 x  13 x 256   ->    13 x  13 x 128  0.011 BFLOPs
   19 upsample            2x    13 x  13 x 128   ->    26 x  26 x 128
   20 route  19 8
   21 conv    256  3 x 3 / 1    26 x  26 x 384   ->    26 x  26 x 256  1.196 BFLOPs
   22 conv    255  1 x 1 / 1    26 x  26 x 256   ->    26 x  26 x 255  0.088 BFLOPs
   23 yolo
...
```

#### DW2TF shapes (valid padding):
```
$ python main.py --cfg data/yolov3-tiny.cfg --weights data/yolov3-tiny.weights --output data/ --prefix yolov3-tiny/

0 Tensor("yolov3-tiny/net1:0", shape=(?, 416, 416, 3), dtype=float32)
1 Tensor("yolov3-tiny/convolutional1/Activation:0", shape=(?, 416, 416, 16), dtype=float32)
2 Tensor("yolov3-tiny/maxpool1/MaxPool:0", shape=(?, 208, 208, 16), dtype=float32)
3 Tensor("yolov3-tiny/convolutional2/Activation:0", shape=(?, 208, 208, 32), dtype=float32)
4 Tensor("yolov3-tiny/maxpool2/MaxPool:0", shape=(?, 104, 104, 32), dtype=float32)
5 Tensor("yolov3-tiny/convolutional3/Activation:0", shape=(?, 104, 104, 64), dtype=float32)
6 Tensor("yolov3-tiny/maxpool3/MaxPool:0", shape=(?, 52, 52, 64), dtype=float32)
7 Tensor("yolov3-tiny/convolutional4/Activation:0", shape=(?, 52, 52, 128), dtype=float32)
8 Tensor("yolov3-tiny/maxpool4/MaxPool:0", shape=(?, 26, 26, 128), dtype=float32)
9 Tensor("yolov3-tiny/convolutional5/Activation:0", shape=(?, 26, 26, 256), dtype=float32)
10 Tensor("yolov3-tiny/maxpool5/MaxPool:0", shape=(?, 13, 13, 256), dtype=float32)
11 Tensor("yolov3-tiny/convolutional6/Activation:0", shape=(?, 13, 13, 512), dtype=float32)
12 Tensor("yolov3-tiny/maxpool6/MaxPool:0", shape=(?, 12, 12, 512), dtype=float32)
13 Tensor("yolov3-tiny/convolutional7/Activation:0", shape=(?, 12, 12, 1024), dtype=float32)
14 Tensor("yolov3-tiny/convolutional8/Activation:0", shape=(?, 12, 12, 256), dtype=float32)
15 Tensor("yolov3-tiny/convolutional9/Activation:0", shape=(?, 12, 12, 512), dtype=float32)
16 Tensor("yolov3-tiny/convolutional10/BiasAdd:0", shape=(?, 12, 12, 255), dtype=float32)
17 Tensor("yolov3-tiny/convolutional10/BiasAdd:0", shape=(?, 12, 12, 255), dtype=float32)
18 Tensor("yolov3-tiny/route1:0", shape=(?, 12, 12, 256), dtype=float32)
19 Tensor("yolov3-tiny/convolutional11/Activation:0", shape=(?, 12, 12, 128), dtype=float32)
20 Tensor("yolov3-tiny/upsample1:0", shape=(?, 24, 24, 128), dtype=float32)
Traceback (most recent call last):
  File "/scratch/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 24 and 26. Shapes are [?,24,24] and [?,26,26]. for 'yolov3-tiny/route2' (op: 'ConcatV2') with input shapes: [?,24,24,128], [?,26,26,128], [] and with computed input tensors: input[2] = <-1>.
...
```
#### DW2TF shapes (same padding):
```
$ python main.py --cfg data/yolov3-tiny.cfg --weights data/yolov3-tiny.weights --output data/ --prefix yolov3-tiny/

0 Tensor("yolov3-tiny/net1:0", shape=(?, 416, 416, 3), dtype=float32)
1 Tensor("yolov3-tiny/convolutional1/Activation:0", shape=(?, 416, 416, 16), dtype=float32)
2 Tensor("yolov3-tiny/maxpool1/MaxPool:0", shape=(?, 208, 208, 16), dtype=float32)
3 Tensor("yolov3-tiny/convolutional2/Activation:0", shape=(?, 208, 208, 32), dtype=float32)
4 Tensor("yolov3-tiny/maxpool2/MaxPool:0", shape=(?, 104, 104, 32), dtype=float32)
5 Tensor("yolov3-tiny/convolutional3/Activation:0", shape=(?, 104, 104, 64), dtype=float32)
6 Tensor("yolov3-tiny/maxpool3/MaxPool:0", shape=(?, 52, 52, 64), dtype=float32)
7 Tensor("yolov3-tiny/convolutional4/Activation:0", shape=(?, 52, 52, 128), dtype=float32)
8 Tensor("yolov3-tiny/maxpool4/MaxPool:0", shape=(?, 26, 26, 128), dtype=float32)
9 Tensor("yolov3-tiny/convolutional5/Activation:0", shape=(?, 26, 26, 256), dtype=float32)
10 Tensor("yolov3-tiny/maxpool5/MaxPool:0", shape=(?, 13, 13, 256), dtype=float32)
11 Tensor("yolov3-tiny/convolutional6/Activation:0", shape=(?, 13, 13, 512), dtype=float32)
12 Tensor("yolov3-tiny/maxpool6/MaxPool:0", shape=(?, 13, 13, 512), dtype=float32)
13 Tensor("yolov3-tiny/convolutional7/Activation:0", shape=(?, 13, 13, 1024), dtype=float32)
14 Tensor("yolov3-tiny/convolutional8/Activation:0", shape=(?, 13, 13, 256), dtype=float32)
15 Tensor("yolov3-tiny/convolutional9/Activation:0", shape=(?, 13, 13, 512), dtype=float32)
16 Tensor("yolov3-tiny/convolutional10/BiasAdd:0", shape=(?, 13, 13, 255), dtype=float32)
17 Tensor("yolov3-tiny/convolutional10/BiasAdd:0", shape=(?, 13, 13, 255), dtype=float32)
18 Tensor("yolov3-tiny/route1:0", shape=(?, 13, 13, 256), dtype=float32)
19 Tensor("yolov3-tiny/convolutional11/Activation:0", shape=(?, 13, 13, 128), dtype=float32)
20 Tensor("yolov3-tiny/upsample1:0", shape=(?, 26, 26, 128), dtype=float32)
21 Tensor("yolov3-tiny/route2:0", shape=(?, 26, 26, 256), dtype=float32)
22 Tensor("yolov3-tiny/convolutional12/Activation:0", shape=(?, 26, 26, 256), dtype=float32)
23 Tensor("yolov3-tiny/convolutional13/BiasAdd:0", shape=(?, 26, 26, 255), dtype=float32)
24 Tensor("yolov3-tiny/convolutional13/BiasAdd:0", shape=(?, 26, 26, 255), dtype=float32)
=> Output layer:  Tensor("yolov3-tiny/convolutional10/BiasAdd:0", shape=(?, 13, 13, 255), dtype=float32)
=> Output layer:  Tensor("yolov3-tiny/convolutional13/BiasAdd:0", shape=(?, 26, 26, 255), dtype=float32)
...
```
